CalculateMultinomLL <- function(counts.raw, ref.probs.mat, transpose.output = TRUE){
  # we assume count vector is generated by a multinomial distribution, parametrized by one of the cell types.
  # For one vector of counts from one cell, we calculate log-likelihood for each of the possible cell types, return the LL matrix.
  # The maximum LL is the most likely cell type for that one cell.
  ll <- as.data.frame(apply(ref.probs.mat, 2, function(prob.vec){
    return(dmultinom(x = counts.raw, prob = prob.vec, log = TRUE))
  }))
  # rownames(ll) <- rownames(ref.probs.mat)
  # colnames(ll) <- colnames(ref.probs.mat)
  colnames(ll) <- "LL"
  if (transpose.output){
    return(t(ll))
  } else {
    return(ll)
  }
}

logsumexp <- function (x) {
  y = max(x)
  y + log(sum(exp(x - y)))
}
softmax <- function (x) {
  exp(x - logsumexp(x))
}


